/// <reference types="next" />
/// <reference types="next/types/global" />
/// <reference types="next/image-types/global" />

// NOTE: This file is auto-generated by Next.js.
// Add custom environment variable types below.

declare namespace NodeJS {
  interface ProcessEnv {
    readonly NODE_ENV: 'development' | 'production' | 'test';

    /**
     * Server-side API URL for fetching channel list
     */
    readonly VIDEO_URI: string;

    /**
     * Client-side (browser) fixed token for streams
     * Must be prefixed with NEXT_PUBLIC to expose to client
     */
    readonly NEXT_PUBLIC_FIXED_TOKEN: string;

    /**
     * Client-side (browser) API URL override, if needed
     */
    readonly NEXT_PUBLIC_VIDEO_URI: string;

    // Add other NEXT_PUBLIC_* environment variables here as needed
  }
}